from django.urls import path

from . import views


urlpatterns = [
    
    path('', views.signIn, name='signIn'),
    path('signUp', views.signUp, name='signUp'),
    path('home', views.home, name='home'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('logout_view', views.logout_view, name='logout_view'),
    path('home/<str:tag>/', views.tag_detail, name='tag_detail'),
    path('like/<str:pk>/', views.likeButton, name='like'),
    path('AllLikes/<str:pk>/', views.LikesForAllPost, name='LikesForAllPost'),
    path('dislikeForAllPost/<str:pk>/', views.dislikeForAllPost, name='dislikeForAllPost'),
    path('dislike/<str:pk>/', views.dislikeButton, name='dislikeButton'),
    path('opinions', views.opinions, name='opinions'),
    path('opinions/<str:pk>/', views.opinionDetail, name='opinionDetail'),
    path('opinions/tag/<str:tag>/', views.tag_ForOpinions, name='tag_ForOpinions'),
    path('AgreeForAllOpinions/<str:pk>/', views.AgreeForAllOpinions, name='AgreeForAllOpinions'),
    path('Agree/<str:pk>/', views.AgreeButton, name='Agree'),
    path('DisagreeForAllOpinions/<str:pk>/', views.DisagreeForAllOpinions, name='DisagreeForAllOpinions'),
    path('Disagree/<str:pk>/', views.DisagreeButton, name='Disagree'),
    path('post/<str:pk>/', views.PostDetail, name='post'),
    path('followersForEachUser/<str:pk>/', views.followersForEachUser, name='followersForEachUser'),
    path('followingForEachUser/<str:pk>/', views.followingForEachUser, name='followingForEachUser'),
    path('Followers/<str:pk>/', views.FollowerButton, name='FollowerButton'),
    path('comments/<str:pk>/', views.CommentsForAllPost, name='comments'),
    path('CreateComments/<str:pk>/', views.CreateComments, name='CreateComments'),
    path('AllUsers', views.AllUsers, name='AllUsers'),
    path('AllProfile', views.AllProfile, name='AllProfile'),
    path('comment/<str:pk>/', views.commentDetail, name='commentForPost'),
    path('deletePost/<str:pk>/', views.deletePost, name='deletePost'),
    path('deleteComment/<str:pk>/', views.deleteComment, name='deleteComment'),
    path('eyesForEachUser/<str:pk>/', views.eyesForEachUser, name='AllEyes'),
    path('CreateEyes/<str:pk>/', views.CreateEyes, name='CreateEyes'),
    path('media', views.media, name='media'),
    path('media/<str:pk>/', views.mediaDetail, name='mediaDetail'),
    path('deleteOpinions/<str:pk>/', views.deleteOpinions, name='deleteOpinions'),
    path('commentsForEachVideo/<str:pk>/', views.commentsForEachVideo, name='commentsForEachVideo'),
    path('createCommentForVideo/<str:pk>/', views.createCommentForVideo, name='createCommentForVideo'),
    path('ViewsForEachVideo/<str:pk>/', views.ViewsForEachVideo, name='ViewsForEachVideo'),
    path('saveViews/<str:pk>/', views.saveViews, name='saveViews'),
    path('AllUsersWhoLoved/<str:pk>/', views.AllUsersWhoLoved, name='AllUsersWhoLoved'),
    path('LovedButton/<str:pk>/', views.LovedButton, name='LovedButton'),
    path('deleteVideo/<str:pk>/', views.deleteVideo, name='deleteVideo'),
    path('commentMedia/<str:pk>/', views.commentMedia, name='commentMedia'),
    path('deleteCommentForVideo/<str:pk>/', views.deleteCommentForVideo, name='deleteCommentForVideo'),
    path('MessagesBetweenTwoUsers/<str:SenderID>/<str:ReciverID>/', views.MessagesBetweenTwoUsers, name='MessagesBetweenTwoUsers'),
    path('updateWhenUserRecives/<str:pk>/', views.updateWhenUserRecives, name='updateWhenUserRecives'),
    path('messagesInbox/<str:pk>/', views.messagesInbox, name='messagesInbox'),
    path('Inbox/<str:pk>/', views.messagePage, name='Inbox'),
    path('chat/<str:SenderID>/<str:ReciverID>/', views.chatPage, name='chat'),
    path('createInbox/<str:SenderID>/<str:ReciverID>/', views.createInbox, name='createInbox'),
    path('sendMessage/<str:SenderID>/<str:ReciverID>/', views.sendMessage, name='sendMessage'),
    path('searchPost', views.searchPost, name='searchPost'),
    path('SearchOpinion', views.SearchOpinion, name='SearchOpinion'),
    path('SearchMedia', views.SearchMedia, name='SearchMedia'),


]